version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: 
          name: Install pip3
          command: sudo apt-get install python3-pip
      - run:
          name: Install requests
          command: pip3 install requests
      - run:
          name: Build
          command: ./.build-script/ci-build
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples